name: Docker Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/playwright-tests:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:buildcache,mode=max

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up X11 for headful testing
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb x11vnc fluxbox
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3

    - name: Run Playwright Tests in Docker (Headful Mode)
      run: |
        echo "Starting Playwright tests in headful mode..."
        docker run --rm \
          --network host \
          -e DISPLAY=:99 \
          -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
          --ipc=host \
          -e BASE_URL="${{ secrets.BASE_URL }}" \
          -e GOOGLE_USERNAME="${{ secrets.GOOGLE_USERNAME }}" \
          -e GOOGLE_PASSWORD="${{ secrets.GOOGLE_PASSWORD }}" \
          -e PROFILE_PICTURE_URL="${{ secrets.PROFILE_PICTURE_URL }}" \
          -e TARGET_YOUTUBE_CHANNEL_ID="${{ secrets.TARGET_YOUTUBE_CHANNEL_ID }}" \
          -e USERNAME="${{ secrets.USERNAME }}" \
          -e PASSWORD="${{ secrets.PASSWORD }}" \
          -e PLAYWRIGHT_HEADLESS=false \
          mcr.microsoft.com/playwright:v1.41.0-focal \
          sh -c "cd /app && npm test"
        echo "Tests completed successfully!"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        echo "All tests passed! Ready for deployment."