name: Docker Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/playwright-tests:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:buildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production
      run: |
        echo "Add your deployment commands here"
        # Example for deploying to a server:
        # ssh user@your-server "docker pull ${{ secrets.DOCKER_USERNAME }}/playwright-tests:latest && docker-compose up -d"