name: Docker Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Debug step to check if secrets exist (remove after fixing)
    - name: Check secrets (DEBUG - REMOVE AFTER FIXING)
      run: |
        echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
        echo "DOCKER_TOKEN length: ${#DOCKER_TOKEN}"
        if [ -z "$DOCKER_USERNAME" ]; then
          echo "❌ DOCKER_USERNAME is empty or not set"
        else
          echo "✅ DOCKER_USERNAME is set"
        fi
        if [ -z "$DOCKER_TOKEN" ]; then
          echo "❌ DOCKER_TOKEN is empty or not set"
        else
          echo "✅ DOCKER_TOKEN is set"
        fi
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    # Try explicit Docker Hub login (remove ecr: auto)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/playwright-tests:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:buildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production
      run: |
        echo "Add your deployment commands here"